### ISSUE TITLE
Mapillary app does not allow anymore to store photos on SDCard?

### ISSUE THREAD

**Issue by severinmenard** [mapillary/UserGuide#14]
Android 7.0 on Moto G5 Play
App version 3.117
Since a few days, maybe the last update, Mapillary stores the photos no more on the micro SDcard in the device but in its internal memory and does not allow to browse upper than /storage/emulated/0 (see the screenshot below) and therefore does not allow to get to the SDcard, while this SDcard is detected by all the other apps in the device. Obviously this is a huge limitation for capture photos during long runs. Is there a way to set the storage location back to the micro SDcard?

![screenshot_20180102-115428](https://user-images.githubusercontent.com/1291055/34487825-be5889ea-efb4-11e7-880c-7ccaeaefd8ea.png)

**Comment by eneerhut** [comment]
@severinmenard thanks for reporting this issue. Sounds odd.
I have shared this issue with our Android dev team to investigate.

In future, please share issues such as this with support@mapillary.com so that they can be handled properly. This repository is not a place for issues and we do not actively maintain it. Don't want anything you report going unanswered :)

Another option for issue reporting is our [issues repository](https://github.com/mapillary/mapillary_issues/issues).
